[2023-02-20T17:53:56.338+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: csv_to_postgres_v01.df_to_postgres manual__2023-02-20T17:53:51.333714+00:00 [queued]>
[2023-02-20T17:53:56.344+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: csv_to_postgres_v01.df_to_postgres manual__2023-02-20T17:53:51.333714+00:00 [queued]>
[2023-02-20T17:53:56.344+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T17:53:56.345+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-20T17:53:56.345+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T17:53:56.353+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): df_to_postgres> on 2023-02-20 17:53:51.333714+00:00
[2023-02-20T17:53:56.358+0000] {standard_task_runner.py:55} INFO - Started process 3453 to run task
[2023-02-20T17:53:56.361+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres_v01', 'df_to_postgres', 'manual__2023-02-20T17:53:51.333714+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/clean_csv_via_s3_and_postgres.py', '--cfg-path', '/tmp/tmp636fafgt']
[2023-02-20T17:53:56.363+0000] {standard_task_runner.py:83} INFO - Job 167: Subtask df_to_postgres
[2023-02-20T17:53:56.413+0000] {task_command.py:388} INFO - Running <TaskInstance: csv_to_postgres_v01.df_to_postgres manual__2023-02-20T17:53:51.333714+00:00 [running]> on host c2aaa60a62e5
[2023-02-20T17:53:56.461+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_to_postgres_v01
AIRFLOW_CTX_TASK_ID=df_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-02-20T17:53:51.333714+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-20T17:53:51.333714+00:00
[2023-02-20T17:53:56.470+0000] {base.py:73} INFO - Using connection ID 'AWS' for task execution.
[2023-02-20T17:53:56.471+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='AWS', conn_type='aws') credentials retrieved from login and password.
[2023-02-20T17:53:57.239+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/clean_csv_via_s3_and_postgres.py", line 67, in df_to_postgres
    return df.colums
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'colums'
[2023-02-20T17:53:57.255+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=csv_to_postgres_v01, task_id=df_to_postgres, execution_date=20230220T175351, start_date=20230220T175356, end_date=20230220T175357
[2023-02-20T17:53:57.264+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 167 for task df_to_postgres ('DataFrame' object has no attribute 'colums'; 3453)
[2023-02-20T17:53:57.325+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-20T17:53:57.342+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
