[2023-02-16T12:44:40.733+0000] {processor.py:153} INFO - Started process (PID=67720) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:44:40.735+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:44:40.737+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:44:40.737+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:44:41.472+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:44:41.466+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:44:41.474+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:44:41.505+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.781 seconds
[2023-02-16T12:45:11.740+0000] {processor.py:153} INFO - Started process (PID=67795) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:45:11.741+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:45:11.743+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:45:11.742+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:45:12.202+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:45:12.200+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:45:12.204+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:45:12.222+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.489 seconds
[2023-02-16T12:45:42.521+0000] {processor.py:153} INFO - Started process (PID=67871) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:45:42.524+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:45:42.525+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:45:42.525+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:45:43.020+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:45:43.013+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:45:43.022+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:45:43.044+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.542 seconds
[2023-02-16T12:46:13.507+0000] {processor.py:153} INFO - Started process (PID=67941) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:46:13.510+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:46:13.512+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:46:13.512+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:46:13.962+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:46:13.960+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:46:13.966+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:46:13.980+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.483 seconds
[2023-02-16T12:46:44.235+0000] {processor.py:153} INFO - Started process (PID=68027) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:46:44.237+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:46:44.239+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:46:44.239+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:46:44.544+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:46:44.543+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:46:44.545+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:46:44.564+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.334 seconds
[2023-02-16T12:47:15.402+0000] {processor.py:153} INFO - Started process (PID=68095) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:47:15.411+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:47:15.414+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:47:15.414+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:47:15.835+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:47:15.834+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:47:15.836+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:47:15.858+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.476 seconds
[2023-02-16T12:47:46.800+0000] {processor.py:153} INFO - Started process (PID=68178) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:47:46.807+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:47:46.811+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:47:46.811+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:47:47.242+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:47:47.240+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:47:47.242+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:47:47.256+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.471 seconds
[2023-02-16T12:48:17.373+0000] {processor.py:153} INFO - Started process (PID=68255) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:48:17.375+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:48:17.376+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:48:17.376+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:48:17.715+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:48:17.714+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:48:17.716+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:48:17.729+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.360 seconds
[2023-02-16T12:48:47.977+0000] {processor.py:153} INFO - Started process (PID=68329) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:48:47.981+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:48:47.985+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:48:47.984+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:48:48.422+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:48:48.421+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:48:48.424+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:48:48.443+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.475 seconds
[2023-02-16T12:49:18.750+0000] {processor.py:153} INFO - Started process (PID=68399) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:49:18.753+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:49:18.756+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:49:18.755+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:49:19.226+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:49:19.224+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:49:19.227+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:49:19.259+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.519 seconds
[2023-02-16T12:49:49.566+0000] {processor.py:153} INFO - Started process (PID=68482) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:49:49.569+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:49:49.571+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:49:49.571+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:49:50.199+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:49:50.197+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:49:50.200+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:49:50.241+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.690 seconds
[2023-02-16T12:50:20.476+0000] {processor.py:153} INFO - Started process (PID=68552) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:50:20.479+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:50:20.481+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:50:20.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:50:20.993+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:50:20.992+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:50:20.995+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:50:21.014+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.548 seconds
[2023-02-16T12:50:51.184+0000] {processor.py:153} INFO - Started process (PID=68635) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:50:51.190+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:50:51.194+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:50:51.194+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:50:51.935+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:50:51.932+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:50:51.936+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:50:52.001+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.829 seconds
[2023-02-16T12:51:22.222+0000] {processor.py:153} INFO - Started process (PID=68710) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:51:22.223+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:51:22.224+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:51:22.224+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:51:22.620+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:51:22.617+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:51:22.621+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:51:22.643+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.424 seconds
[2023-02-16T12:51:53.182+0000] {processor.py:153} INFO - Started process (PID=68788) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:51:53.187+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:51:53.193+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:51:53.192+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:51:53.847+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:51:53.844+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:51:53.849+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:51:53.870+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.698 seconds
[2023-02-16T12:52:24.185+0000] {processor.py:153} INFO - Started process (PID=68863) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:52:24.186+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:52:24.188+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:52:24.188+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:52:24.450+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:52:24.448+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:52:24.451+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:52:24.470+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.289 seconds
[2023-02-16T12:52:54.897+0000] {processor.py:153} INFO - Started process (PID=68933) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:52:54.898+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:52:54.899+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:52:54.899+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:52:55.140+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:52:55.138+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:52:55.141+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:52:55.157+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.265 seconds
[2023-02-16T12:53:25.833+0000] {processor.py:153} INFO - Started process (PID=69012) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:53:25.836+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:53:25.837+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:53:25.837+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:53:26.105+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:53:26.101+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:53:26.108+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:53:26.149+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.322 seconds
[2023-02-16T12:53:56.391+0000] {processor.py:153} INFO - Started process (PID=69084) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:53:56.392+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:53:56.393+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:53:56.393+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:53:56.867+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:53:56.865+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:53:56.868+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:53:56.904+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.517 seconds
[2023-02-16T12:54:27.414+0000] {processor.py:153} INFO - Started process (PID=69164) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:54:27.420+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:54:27.425+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:54:27.424+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:54:28.001+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:54:27.998+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:54:28.002+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:54:28.026+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.636 seconds
[2023-02-16T12:54:58.238+0000] {processor.py:153} INFO - Started process (PID=69230) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:54:58.245+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:54:58.250+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:54:58.249+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:54:58.863+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:54:58.857+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:54:58.867+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:54:58.888+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.662 seconds
[2023-02-16T12:55:29.283+0000] {processor.py:153} INFO - Started process (PID=69308) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:55:29.286+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:55:29.287+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:55:29.287+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:55:29.941+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:55:29.935+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:55:29.946+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:55:29.975+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.700 seconds
[2023-02-16T12:55:48.029+0000] {processor.py:153} INFO - Started process (PID=69358) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:55:48.035+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:55:48.038+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:55:48.038+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:55:49.866+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:55:49.862+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:55:49.867+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:55:49.932+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 1.928 seconds
[2023-02-16T12:56:20.927+0000] {processor.py:153} INFO - Started process (PID=69429) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:56:20.931+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:56:20.934+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:56:20.933+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:56:21.368+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:56:21.367+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:56:21.370+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:56:21.414+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.501 seconds
[2023-02-16T12:56:51.544+0000] {processor.py:153} INFO - Started process (PID=69511) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:56:51.546+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:56:51.548+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:56:51.547+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:56:51.980+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:56:51.978+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:56:51.981+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:56:52.027+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.492 seconds
[2023-02-16T12:57:22.865+0000] {processor.py:153} INFO - Started process (PID=69581) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:57:22.867+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:57:22.869+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:57:22.869+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:57:23.278+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:57:23.276+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:57:23.279+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:57:23.311+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.455 seconds
[2023-02-16T12:57:53.734+0000] {processor.py:153} INFO - Started process (PID=69663) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:57:53.736+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:57:53.737+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:57:53.737+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:57:54.162+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:57:54.158+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:57:54.165+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:57:54.191+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.463 seconds
[2023-02-16T12:58:24.500+0000] {processor.py:153} INFO - Started process (PID=69733) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:58:24.507+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:58:24.512+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:58:24.511+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:58:24.986+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:58:24.984+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:58:24.987+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:58:25.010+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.520 seconds
[2023-02-16T12:58:55.568+0000] {processor.py:153} INFO - Started process (PID=69816) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:58:55.574+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:58:55.578+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:58:55.577+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:58:56.309+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:58:56.287+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:58:56.313+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:58:56.744+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 1.204 seconds
[2023-02-16T12:59:27.247+0000] {processor.py:153} INFO - Started process (PID=69885) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:59:27.251+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:59:27.261+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:59:27.260+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:59:27.718+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:59:27.716+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 28, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:59:27.719+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:59:27.746+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.512 seconds
[2023-02-16T12:59:55.764+0000] {processor.py:153} INFO - Started process (PID=69955) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:59:55.766+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T12:59:55.769+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:59:55.768+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:59:56.204+0000] {logging_mixin.py:137} INFO - [2023-02-16T12:59:56.167+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T12:59:56.206+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T12:59:56.233+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.475 seconds
[2023-02-16T13:00:27.433+0000] {processor.py:153} INFO - Started process (PID=70034) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:00:27.440+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:00:27.445+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:00:27.444+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:00:28.151+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:00:28.149+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:00:28.153+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:00:28.173+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.776 seconds
[2023-02-16T13:00:58.722+0000] {processor.py:153} INFO - Started process (PID=70101) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:00:58.727+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:00:58.729+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:00:58.729+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:00:59.250+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:00:59.247+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:00:59.252+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:00:59.289+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.577 seconds
[2023-02-16T13:01:29.967+0000] {processor.py:153} INFO - Started process (PID=70183) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:01:29.971+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:01:29.974+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:01:29.973+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:01:30.733+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:01:30.666+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:01:30.743+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:01:30.892+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.935 seconds
[2023-02-16T13:02:01.266+0000] {processor.py:153} INFO - Started process (PID=70253) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:02:01.275+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:02:01.282+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:02:01.280+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:02:01.883+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:02:01.877+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:02:01.885+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:02:01.940+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.686 seconds
[2023-02-16T13:02:32.553+0000] {processor.py:153} INFO - Started process (PID=70335) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:02:32.556+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:02:32.558+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:02:32.558+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:02:33.241+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:02:33.233+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:02:33.244+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:02:33.288+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.743 seconds
[2023-02-16T13:03:03.486+0000] {processor.py:153} INFO - Started process (PID=70405) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:03:03.489+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:03:03.491+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:03:03.491+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:03:03.925+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:03:03.922+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:03:03.925+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:03:03.959+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.484 seconds
[2023-02-16T13:03:35.422+0000] {processor.py:153} INFO - Started process (PID=70486) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:03:35.428+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:03:35.435+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:03:35.434+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:03:36.652+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:03:36.636+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:03:36.659+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:03:36.722+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 1.308 seconds
[2023-02-16T13:04:07.560+0000] {processor.py:153} INFO - Started process (PID=70557) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:04:07.562+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:04:07.563+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:04:07.563+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:04:08.025+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:04:08.008+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:04:08.029+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:04:08.061+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.508 seconds
[2023-02-16T13:04:38.440+0000] {processor.py:153} INFO - Started process (PID=70627) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:04:38.444+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:04:38.458+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:04:38.458+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:04:40.187+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:04:40.173+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:04:40.200+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:04:40.377+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 1.946 seconds
[2023-02-16T13:04:51.612+0000] {processor.py:153} INFO - Started process (PID=70670) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:04:51.616+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:04:51.622+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:04:51.621+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:04:52.225+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:04:52.218+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from airflow.tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'airflow.tests'
[2023-02-16T13:04:52.228+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:04:52.276+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.686 seconds
[2023-02-16T13:05:02.796+0000] {processor.py:153} INFO - Started process (PID=70702) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:05:02.801+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:05:02.803+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:05:02.803+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:05:03.421+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:05:03.418+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:05:03.422+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:05:03.489+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.709 seconds
[2023-02-16T13:05:34.206+0000] {processor.py:153} INFO - Started process (PID=70784) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:05:34.212+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:05:34.222+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:05:34.221+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:05:35.021+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:05:35.017+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:05:35.022+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:05:35.051+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.858 seconds
[2023-02-16T13:06:05.244+0000] {processor.py:153} INFO - Started process (PID=70854) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:06:05.248+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:06:05.250+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:06:05.250+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:06:05.721+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:06:05.716+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:06:05.722+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:06:05.759+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.523 seconds
[2023-02-16T13:06:35.934+0000] {processor.py:153} INFO - Started process (PID=70931) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:06:35.936+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:06:35.938+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:06:35.938+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:06:36.549+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:06:36.545+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:06:36.551+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:06:36.609+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.680 seconds
[2023-02-16T13:07:07.148+0000] {processor.py:153} INFO - Started process (PID=71006) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:07:07.153+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:07:07.155+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:07:07.155+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:07:07.591+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:07:07.587+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:07:07.592+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:07:07.633+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.491 seconds
[2023-02-16T13:07:38.217+0000] {processor.py:153} INFO - Started process (PID=71085) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:07:38.221+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:07:38.222+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:07:38.222+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:07:38.742+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:07:38.739+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:07:38.743+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:07:38.790+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.579 seconds
[2023-02-16T13:08:09.305+0000] {processor.py:153} INFO - Started process (PID=71160) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:08:09.309+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:08:09.314+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:08:09.313+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:08:09.687+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:08:09.683+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:08:09.689+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:08:09.712+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.414 seconds
[2023-02-16T13:08:39.942+0000] {processor.py:153} INFO - Started process (PID=71238) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:08:39.944+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:08:39.945+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:08:39.945+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:08:40.551+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:08:40.535+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:08:40.552+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:08:40.602+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.672 seconds
[2023-02-16T13:09:11.320+0000] {processor.py:153} INFO - Started process (PID=71311) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:09:11.323+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:09:11.325+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:09:11.325+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:09:11.702+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:09:11.700+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:09:11.703+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:09:11.719+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.410 seconds
[2023-02-16T13:09:42.167+0000] {processor.py:153} INFO - Started process (PID=71393) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:09:42.180+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:09:42.186+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:09:42.185+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:09:42.900+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:09:42.864+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:09:42.904+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:09:42.942+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.782 seconds
[2023-02-16T13:10:13.752+0000] {processor.py:153} INFO - Started process (PID=71465) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:10:13.756+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:10:13.757+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:10:13.757+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:10:14.107+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:10:14.100+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:10:14.109+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:10:14.133+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.390 seconds
[2023-02-16T13:10:44.226+0000] {processor.py:153} INFO - Started process (PID=71547) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:10:44.228+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:10:44.230+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:10:44.229+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:10:44.703+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:10:44.699+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 12, in <module>
    from tests.system.providers.amazon.aws.utils import SystemTestContextBuilder
ModuleNotFoundError: No module named 'tests.system'
[2023-02-16T13:10:44.705+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:10:44.767+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.546 seconds
[2023-02-16T13:11:14.575+0000] {processor.py:153} INFO - Started process (PID=71617) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:11:14.581+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:11:14.584+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:11:14.583+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:11:16.109+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:11:16.157+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 1.599 seconds
[2023-02-16T13:11:21.506+0000] {processor.py:153} INFO - Started process (PID=71630) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:11:21.509+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:11:21.514+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:11:21.513+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:11:22.786+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:11:22.780+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 14, in <module>
    'retry_delay': timedelta(minutes=5),
NameError: name 'timedelta' is not defined
[2023-02-16T13:11:22.788+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:11:22.838+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 1.343 seconds
[2023-02-16T13:11:31.714+0000] {processor.py:153} INFO - Started process (PID=71667) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:11:31.723+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:11:31.727+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:11:31.727+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:11:33.148+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:11:33.145+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 14, in <module>
    'retry_delay': timedelta(minutes=5),
NameError: name 'timedelta' is not defined
[2023-02-16T13:11:33.149+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:11:33.173+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 1.472 seconds
[2023-02-16T13:12:03.541+0000] {processor.py:153} INFO - Started process (PID=71738) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:12:03.545+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:12:03.547+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:12:03.546+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:12:04.257+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:12:04.252+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 14, in <module>
    'retry_delay': timedelta(minutes=5),
NameError: name 'timedelta' is not defined
[2023-02-16T13:12:04.258+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:12:04.284+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.753 seconds
[2023-02-16T13:12:34.699+0000] {processor.py:153} INFO - Started process (PID=71822) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:12:34.704+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:12:34.710+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:12:34.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:12:35.526+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:12:35.520+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 14, in <module>
    'retry_delay': timedelta(minutes=5),
NameError: name 'timedelta' is not defined
[2023-02-16T13:12:35.527+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:12:35.556+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.866 seconds
[2023-02-16T13:12:49.188+0000] {processor.py:153} INFO - Started process (PID=71855) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:12:49.190+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:12:49.192+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:12:49.191+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:12:49.200+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:12:49.198+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:12:49.200+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:12:49.354+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.172 seconds
[2023-02-16T13:13:19.835+0000] {processor.py:153} INFO - Started process (PID=71926) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:13:19.838+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:13:19.839+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:13:19.839+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:13:19.847+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:13:19.845+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:13:19.848+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:13:19.883+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.056 seconds
[2023-02-16T13:13:21.947+0000] {processor.py:153} INFO - Started process (PID=71931) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:13:21.953+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:13:21.956+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:13:21.956+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:13:21.977+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:13:21.971+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:13:21.978+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:13:22.015+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.074 seconds
[2023-02-16T13:13:52.429+0000] {processor.py:153} INFO - Started process (PID=72002) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:13:52.438+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:13:52.441+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:13:52.441+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:13:52.491+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:13:52.482+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:13:52.497+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:13:52.541+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.146 seconds
[2023-02-16T13:14:23.187+0000] {processor.py:153} INFO - Started process (PID=72084) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:14:23.189+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:14:23.192+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:14:23.192+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:14:23.200+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:14:23.198+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:14:23.201+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:14:23.244+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.064 seconds
[2023-02-16T13:14:53.585+0000] {processor.py:153} INFO - Started process (PID=72155) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:14:53.587+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:14:53.589+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:14:53.589+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:14:53.598+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:14:53.595+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:14:53.599+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:14:53.645+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.069 seconds
[2023-02-16T13:15:23.822+0000] {processor.py:153} INFO - Started process (PID=72235) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:15:23.826+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:15:23.828+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:15:23.828+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:15:23.834+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:15:23.833+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:15:23.834+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:15:23.860+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.045 seconds
[2023-02-16T13:15:54.110+0000] {processor.py:153} INFO - Started process (PID=72305) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:15:54.113+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:15:54.114+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:15:54.114+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:15:54.122+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:15:54.120+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:15:54.123+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:15:54.169+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.067 seconds
[2023-02-16T13:16:24.498+0000] {processor.py:153} INFO - Started process (PID=72387) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:16:24.501+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:16:24.502+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:16:24.502+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:16:24.509+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:16:24.507+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:16:24.510+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:16:24.539+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.053 seconds
[2023-02-16T13:16:55.108+0000] {processor.py:153} INFO - Started process (PID=72457) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:16:55.111+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:16:55.112+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:16:55.112+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:16:55.127+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:16:55.118+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:16:55.131+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:16:55.177+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.082 seconds
[2023-02-16T13:17:25.367+0000] {processor.py:153} INFO - Started process (PID=72539) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:17:25.371+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:17:25.373+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:17:25.372+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:17:25.381+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:17:25.379+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:17:25.382+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:17:25.407+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.047 seconds
[2023-02-16T13:17:55.759+0000] {processor.py:153} INFO - Started process (PID=72610) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:17:55.766+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:17:55.768+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:17:55.768+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:17:55.783+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:17:55.781+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:17:55.784+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:17:55.815+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.068 seconds
[2023-02-16T13:18:26.702+0000] {processor.py:153} INFO - Started process (PID=72691) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:18:26.704+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:18:26.705+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:18:26.705+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:18:26.719+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:18:26.714+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:18:26.725+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:18:26.770+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.077 seconds
[2023-02-16T13:18:57.239+0000] {processor.py:153} INFO - Started process (PID=72761) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:18:57.241+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:18:57.243+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:18:57.242+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:18:57.251+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:18:57.248+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:18:57.252+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:18:57.300+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.081 seconds
[2023-02-16T13:19:28.159+0000] {processor.py:153} INFO - Started process (PID=72843) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:19:28.162+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:19:28.164+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:19:28.164+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:19:28.173+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:19:28.170+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:19:28.174+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:19:28.216+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.066 seconds
[2023-02-16T13:19:58.810+0000] {processor.py:153} INFO - Started process (PID=72914) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:19:58.812+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:19:58.813+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:19:58.813+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:19:58.821+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:19:58.819+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:19:58.822+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:19:58.851+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.048 seconds
[2023-02-16T13:20:29.213+0000] {processor.py:153} INFO - Started process (PID=72996) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:20:29.215+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:20:29.216+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:20:29.216+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:20:29.222+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:20:29.220+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:20:29.222+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:20:29.242+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.033 seconds
[2023-02-16T13:20:59.925+0000] {processor.py:153} INFO - Started process (PID=73065) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:20:59.928+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:20:59.929+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:20:59.929+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:20:59.938+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:20:59.936+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:20:59.939+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:20:59.964+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.049 seconds
[2023-02-16T13:21:30.133+0000] {processor.py:153} INFO - Started process (PID=73147) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:21:30.134+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:21:30.135+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:21:30.135+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:21:30.153+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:21:30.149+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:21:30.155+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:21:30.188+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.061 seconds
[2023-02-16T13:22:00.458+0000] {processor.py:153} INFO - Started process (PID=73217) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:22:00.460+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:22:00.461+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:22:00.461+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:22:00.475+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:22:00.467+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:22:00.477+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:22:00.513+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.062 seconds
[2023-02-16T13:22:30.937+0000] {processor.py:153} INFO - Started process (PID=73301) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:22:30.940+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:22:30.942+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:22:30.942+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:22:30.949+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:22:30.948+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:22:30.952+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:22:30.978+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.053 seconds
[2023-02-16T13:23:01.233+0000] {processor.py:153} INFO - Started process (PID=73372) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:23:01.236+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:23:01.238+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:23:01.238+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:23:01.247+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:23:01.244+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:23:01.248+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:23:01.291+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.069 seconds
[2023-02-16T13:23:31.444+0000] {processor.py:153} INFO - Started process (PID=73453) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:23:31.446+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:23:31.447+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:23:31.447+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:23:31.454+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:23:31.452+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:23:31.454+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:23:31.489+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.051 seconds
[2023-02-16T13:24:01.858+0000] {processor.py:153} INFO - Started process (PID=73523) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:24:01.862+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:24:01.863+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:24:01.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:24:01.869+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:24:01.868+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:24:01.870+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:24:01.912+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.071 seconds
[2023-02-16T13:24:32.297+0000] {processor.py:153} INFO - Started process (PID=73605) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:24:32.301+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:24:32.306+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:24:32.306+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:24:32.347+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:24:32.345+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:24:32.348+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:24:32.381+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.097 seconds
[2023-02-16T13:25:02.747+0000] {processor.py:153} INFO - Started process (PID=73675) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:25:02.756+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:25:02.758+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:25:02.758+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:25:02.766+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:25:02.764+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:25:02.767+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:25:02.803+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.070 seconds
[2023-02-16T13:25:33.225+0000] {processor.py:153} INFO - Started process (PID=73756) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:25:33.229+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:25:33.232+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:25:33.231+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:25:33.239+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:25:33.238+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:25:33.240+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:25:33.285+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.081 seconds
[2023-02-16T13:26:04.055+0000] {processor.py:153} INFO - Started process (PID=73826) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:26:04.058+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:26:04.060+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:26:04.059+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:26:04.081+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:26:04.071+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:26:04.085+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:26:04.136+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.093 seconds
[2023-02-16T13:26:11.284+0000] {processor.py:153} INFO - Started process (PID=73843) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:26:11.287+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:26:11.289+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:26:11.289+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:26:11.306+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:26:11.304+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:26:11.309+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:26:11.411+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.135 seconds
[2023-02-16T13:26:23.221+0000] {processor.py:153} INFO - Started process (PID=73874) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:26:23.228+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:26:23.230+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:26:23.230+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:26:23.238+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:26:23.236+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:26:23.239+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:26:23.266+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.052 seconds
[2023-02-16T13:26:53.539+0000] {processor.py:153} INFO - Started process (PID=73950) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:26:53.543+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:26:53.544+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:26:53.544+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:26:53.566+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:26:53.563+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:26:53.568+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:26:53.628+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.099 seconds
[2023-02-16T13:27:24.229+0000] {processor.py:153} INFO - Started process (PID=74020) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:27:24.232+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:27:24.234+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:27:24.234+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:27:24.241+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:27:24.239+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:27:24.243+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:27:24.287+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.064 seconds
[2023-02-16T13:27:54.823+0000] {processor.py:153} INFO - Started process (PID=74101) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:27:54.829+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:27:54.833+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:27:54.832+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:27:54.846+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:27:54.844+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 39
    Define a PythonOperator that calls the read_csv_drop_na_write_s3() function:
           ^
SyntaxError: invalid syntax
[2023-02-16T13:27:54.847+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:27:54.909+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.092 seconds
[2023-02-16T13:27:58.854+0000] {processor.py:153} INFO - Started process (PID=74115) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:27:58.857+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:27:58.860+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:27:58.859+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:27:58.887+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:27:58.885+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 46
    Define the dependencies between the tasks:
             ^
SyntaxError: invalid syntax
[2023-02-16T13:27:58.889+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:27:58.954+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.111 seconds
[2023-02-16T13:28:23.902+0000] {processor.py:153} INFO - Started process (PID=74179) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:28:23.905+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:28:23.910+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:28:23.910+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:28:25.057+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:28:25.039+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_local_to_S3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_local_to_S3.py", line 14, in <module>
    'retry_delay': timedelta(minutes=5),
NameError: name 'timedelta' is not defined
[2023-02-16T13:28:25.066+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:28:25.114+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 1.234 seconds
[2023-02-16T13:28:53.238+0000] {processor.py:153} INFO - Started process (PID=74250) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:28:53.273+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:28:53.278+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:28:53.277+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:28:54.319+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:28:54.715+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:28:54.714+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:read_csv_drop_na_write_s3
[2023-02-16T13:28:54.735+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:28:54.735+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:read_csv_drop_na_write_s3
[2023-02-16T13:28:54.745+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:28:54.745+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:read_csv_drop_na_write_s3
[2023-02-16T13:28:54.748+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:28:54.746+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:28:54.766+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:28:54.766+0000] {dag.py:2711} INFO - Creating ORM DAG for read_csv_drop_na_write_s3
[2023-02-16T13:28:54.778+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:28:54.778+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:28:54.823+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 1.674 seconds
[2023-02-16T13:29:25.274+0000] {processor.py:153} INFO - Started process (PID=74321) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:29:25.277+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:29:25.281+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:29:25.280+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:29:25.651+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:29:25.688+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:29:25.687+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:29:25.734+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:29:25.734+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:29:25.748+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.497 seconds
[2023-02-16T13:29:56.836+0000] {processor.py:153} INFO - Started process (PID=74404) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:29:56.838+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:29:56.839+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:29:56.839+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:29:57.160+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:29:57.205+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:29:57.204+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:29:57.224+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:29:57.224+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:29:57.237+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.415 seconds
[2023-02-16T13:30:27.454+0000] {processor.py:153} INFO - Started process (PID=74475) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:30:27.463+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:30:27.468+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:30:27.468+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:30:27.787+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:30:27.835+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:30:27.835+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:30:27.856+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:30:27.855+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:30:27.868+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.428 seconds
[2023-02-16T13:30:58.772+0000] {processor.py:153} INFO - Started process (PID=74559) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:30:58.775+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:30:58.776+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:30:58.776+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:30:59.147+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:30:59.186+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:30:59.186+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:30:59.216+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:30:59.216+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:30:59.230+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.464 seconds
[2023-02-16T13:31:29.725+0000] {processor.py:153} INFO - Started process (PID=74629) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:31:29.728+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:31:29.730+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:31:29.729+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:31:30.074+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:31:30.114+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:31:30.114+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:31:30.136+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:31:30.136+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:31:30.149+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.448 seconds
[2023-02-16T13:32:00.587+0000] {processor.py:153} INFO - Started process (PID=74710) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:32:00.591+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:32:00.594+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:32:00.593+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:32:01.005+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:32:01.055+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:32:01.054+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:32:01.079+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:32:01.079+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:32:01.092+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.512 seconds
[2023-02-16T13:32:31.552+0000] {processor.py:153} INFO - Started process (PID=74780) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:32:31.554+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:32:31.556+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:32:31.555+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:32:31.901+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:32:31.929+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:32:31.929+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:32:31.962+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:32:31.962+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:32:31.974+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.427 seconds
[2023-02-16T13:33:02.859+0000] {processor.py:153} INFO - Started process (PID=74864) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:33:02.862+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:33:02.863+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:33:02.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:33:03.278+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:33:03.328+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:33:03.328+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:33:03.358+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:33:03.358+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:33:03.373+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.524 seconds
[2023-02-16T13:33:34.175+0000] {processor.py:153} INFO - Started process (PID=74935) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:33:34.183+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:33:34.185+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:33:34.185+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:33:34.594+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:33:34.632+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:33:34.632+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:33:34.655+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:33:34.654+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:33:34.668+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.510 seconds
[2023-02-16T13:34:05.638+0000] {processor.py:153} INFO - Started process (PID=75019) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:34:05.641+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:34:05.642+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:34:05.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:34:06.064+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:34:06.110+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:34:06.110+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:34:06.146+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:34:06.146+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:34:06.163+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.543 seconds
[2023-02-16T13:34:36.783+0000] {processor.py:153} INFO - Started process (PID=75090) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:34:36.785+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:34:36.787+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:34:36.787+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:34:37.241+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:34:37.273+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:34:37.272+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:34:37.292+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:34:37.292+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:34:37.302+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.529 seconds
[2023-02-16T13:35:07.959+0000] {processor.py:153} INFO - Started process (PID=75173) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:35:07.985+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:35:07.988+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:35:07.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:35:08.388+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:35:08.415+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:35:08.415+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:35:08.435+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:35:08.435+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:35:08.451+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.505 seconds
[2023-02-16T13:35:38.560+0000] {processor.py:153} INFO - Started process (PID=75244) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:35:38.563+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:35:38.564+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:35:38.564+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:35:38.951+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:35:38.992+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:35:38.992+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:35:39.019+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:35:39.019+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:35:39.058+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.509 seconds
[2023-02-16T13:36:09.483+0000] {processor.py:153} INFO - Started process (PID=75326) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:36:09.486+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:36:09.487+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:36:09.487+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:36:09.902+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:36:09.926+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:36:09.926+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:36:09.957+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:36:09.957+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:36:09.972+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.508 seconds
[2023-02-16T13:36:40.324+0000] {processor.py:153} INFO - Started process (PID=75397) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:36:40.327+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:36:40.329+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:36:40.329+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:36:40.774+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:36:40.820+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:36:40.820+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:36:40.850+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:36:40.850+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:36:40.869+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.556 seconds
[2023-02-16T13:37:11.059+0000] {processor.py:153} INFO - Started process (PID=75480) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:37:11.061+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:37:11.063+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:37:11.062+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:37:11.437+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:37:11.461+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:37:11.461+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:37:11.478+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:37:11.478+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:37:11.493+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.439 seconds
[2023-02-16T13:37:41.677+0000] {processor.py:153} INFO - Started process (PID=75551) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:37:41.683+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:37:41.686+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:37:41.686+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:37:42.066+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:37:42.103+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:37:42.103+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:37:42.125+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:37:42.124+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:37:42.136+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.474 seconds
[2023-02-16T13:38:12.234+0000] {processor.py:153} INFO - Started process (PID=75639) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:38:12.235+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:38:12.237+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:38:12.236+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:38:12.613+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:38:12.638+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:38:12.638+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:38:12.657+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:38:12.656+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:38:12.673+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.445 seconds
[2023-02-16T13:38:43.032+0000] {processor.py:153} INFO - Started process (PID=75708) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:38:43.035+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:38:43.037+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:38:43.036+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:38:43.439+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:38:43.475+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:38:43.474+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:38:43.493+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:38:43.493+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:38:43.504+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.483 seconds
[2023-02-16T13:39:13.933+0000] {processor.py:153} INFO - Started process (PID=75792) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:39:13.938+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:39:13.939+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:39:13.939+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:39:14.307+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:39:14.329+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:39:14.329+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:39:14.354+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:39:14.354+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:39:14.371+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.448 seconds
[2023-02-16T13:39:44.699+0000] {processor.py:153} INFO - Started process (PID=75862) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:39:44.704+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:39:44.710+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:39:44.709+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:39:45.083+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:39:45.109+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:39:45.108+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:39:45.127+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:39:45.127+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:39:45.137+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.445 seconds
[2023-02-16T13:40:15.530+0000] {processor.py:153} INFO - Started process (PID=75946) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:40:15.533+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:40:15.534+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:40:15.534+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:40:15.900+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:40:15.924+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:40:15.924+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:40:15.951+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:40:15.951+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:40:15.962+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.439 seconds
[2023-02-16T13:40:46.424+0000] {processor.py:153} INFO - Started process (PID=76018) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:40:46.427+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:40:46.429+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:40:46.429+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:40:46.842+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:40:46.886+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:40:46.885+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:40:46.909+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:40:46.909+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:40:46.924+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.518 seconds
[2023-02-16T13:41:17.023+0000] {processor.py:153} INFO - Started process (PID=76104) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:41:17.026+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:41:17.027+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:41:17.026+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:41:17.436+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:41:17.478+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:41:17.477+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:41:17.503+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:41:17.503+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:41:17.522+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.506 seconds
[2023-02-16T13:41:47.773+0000] {processor.py:153} INFO - Started process (PID=76172) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:41:47.777+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:41:47.778+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:41:47.778+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:41:48.199+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:41:48.223+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:41:48.222+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:41:48.240+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:41:48.240+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:41:48.250+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.487 seconds
[2023-02-16T13:42:18.394+0000] {processor.py:153} INFO - Started process (PID=76255) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:42:18.396+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:42:18.398+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:42:18.398+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:42:18.764+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:42:18.801+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:42:18.800+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:42:18.819+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:42:18.819+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:42:18.829+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.441 seconds
[2023-02-16T13:42:49.474+0000] {processor.py:153} INFO - Started process (PID=76326) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:42:49.477+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:42:49.478+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:42:49.478+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:42:49.856+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:42:49.877+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:42:49.877+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:42:49.895+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:42:49.894+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:42:49.905+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.440 seconds
[2023-02-16T13:43:20.253+0000] {processor.py:153} INFO - Started process (PID=76411) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:43:20.256+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:43:20.258+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:43:20.257+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:43:20.598+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:43:20.629+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:43:20.629+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:43:20.649+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:43:20.649+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:43:20.661+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.422 seconds
[2023-02-16T13:43:51.303+0000] {processor.py:153} INFO - Started process (PID=76482) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:43:51.311+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:43:51.315+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:43:51.315+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:43:51.798+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:43:51.826+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:43:51.826+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:43:51.866+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:43:51.866+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:43:51.880+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.593 seconds
[2023-02-16T13:44:22.140+0000] {processor.py:153} INFO - Started process (PID=76565) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:44:22.146+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:44:22.148+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:44:22.148+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:44:22.628+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:44:22.663+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:44:22.663+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:44:22.685+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:44:22.685+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:44:22.697+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.566 seconds
[2023-02-16T13:44:53.126+0000] {processor.py:153} INFO - Started process (PID=76636) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:44:53.133+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:44:53.139+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:44:53.138+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:44:54.352+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:44:54.384+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:44:54.383+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:44:54.415+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:44:54.415+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:44:54.428+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 1.332 seconds
[2023-02-16T13:45:24.716+0000] {processor.py:153} INFO - Started process (PID=76719) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:45:24.718+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:45:24.720+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:45:24.720+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:45:25.151+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:45:25.184+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:45:25.183+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:45:25.204+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:45:25.204+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:45:25.215+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.509 seconds
[2023-02-16T13:45:55.585+0000] {processor.py:153} INFO - Started process (PID=76791) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:45:55.590+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:45:55.591+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:45:55.590+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:45:55.951+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:45:55.973+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:45:55.972+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:45:55.994+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:45:55.994+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:45:56.013+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.441 seconds
[2023-02-16T13:46:26.240+0000] {processor.py:153} INFO - Started process (PID=76874) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:46:26.243+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:46:26.245+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:46:26.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:46:26.589+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:46:26.612+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:46:26.612+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:46:26.638+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:46:26.638+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:46:26.649+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.422 seconds
[2023-02-16T13:46:57.192+0000] {processor.py:153} INFO - Started process (PID=76945) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:46:57.195+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:46:57.196+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:46:57.196+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:46:57.595+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:46:57.619+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:46:57.619+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:46:57.644+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:46:57.644+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:46:57.655+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.470 seconds
[2023-02-16T13:47:28.625+0000] {processor.py:153} INFO - Started process (PID=77028) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:47:28.632+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:47:28.635+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:47:28.634+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:47:29.076+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:47:29.100+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:47:29.099+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:47:29.117+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:47:29.117+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:47:29.127+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.514 seconds
[2023-02-16T13:48:00.051+0000] {processor.py:153} INFO - Started process (PID=77107) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:48:00.055+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:48:00.058+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:48:00.058+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:48:00.461+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:48:00.502+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:48:00.502+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:48:00.555+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:48:00.554+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:48:00.631+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.591 seconds
[2023-02-16T13:48:30.734+0000] {processor.py:153} INFO - Started process (PID=77186) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:48:30.737+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:48:30.738+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:48:30.738+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:48:31.131+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:48:31.202+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:48:31.202+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:48:31.260+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:48:31.259+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:48:31.295+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.569 seconds
[2023-02-16T13:49:01.470+0000] {processor.py:153} INFO - Started process (PID=77263) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:49:01.474+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:49:01.480+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:49:01.479+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:49:01.956+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:49:01.988+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:49:01.988+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:49:02.011+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:49:02.011+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:49:02.025+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.572 seconds
[2023-02-16T13:49:32.781+0000] {processor.py:153} INFO - Started process (PID=77336) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:49:32.784+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:49:32.786+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:49:32.786+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:49:33.138+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:49:33.165+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:49:33.164+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:49:33.198+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:49:33.198+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:49:33.214+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.450 seconds
[2023-02-16T13:50:03.657+0000] {processor.py:153} INFO - Started process (PID=77407) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:50:03.662+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:50:03.664+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:50:03.664+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:50:04.126+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:50:04.161+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:50:04.160+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:50:04.194+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:50:04.194+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:50:04.207+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.572 seconds
[2023-02-16T13:50:34.362+0000] {processor.py:153} INFO - Started process (PID=77490) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:50:34.365+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:50:34.366+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:50:34.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:50:34.753+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:50:34.819+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:50:34.819+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:50:34.847+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:50:34.847+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:50:34.860+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.508 seconds
[2023-02-16T13:51:05.059+0000] {processor.py:153} INFO - Started process (PID=77560) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:51:05.062+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:51:05.063+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:51:05.063+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:51:05.467+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:51:05.511+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:51:05.511+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:51:05.537+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:51:05.537+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:51:05.550+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.514 seconds
[2023-02-16T13:51:36.460+0000] {processor.py:153} INFO - Started process (PID=77643) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:51:36.462+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:51:36.464+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:51:36.463+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:51:36.916+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:51:36.950+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:51:36.950+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:51:36.974+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:51:36.973+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:51:36.987+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.536 seconds
[2023-02-16T13:52:07.925+0000] {processor.py:153} INFO - Started process (PID=77722) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:52:07.928+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:52:07.931+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:52:07.931+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:52:08.426+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:52:08.586+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:52:08.585+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:52:08.998+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:52:08.998+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:52:09.097+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 1.192 seconds
[2023-02-16T13:52:39.568+0000] {processor.py:153} INFO - Started process (PID=77802) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:52:39.582+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:52:39.585+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:52:39.584+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:52:39.846+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:52:39.866+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:52:39.866+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:52:39.883+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:52:39.883+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:52:39.893+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.348 seconds
[2023-02-16T13:53:10.080+0000] {processor.py:153} INFO - Started process (PID=77886) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:53:10.082+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:53:10.083+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:53:10.083+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:53:10.391+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:53:10.416+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:53:10.415+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:53:10.439+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:53:10.439+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:53:10.452+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.376 seconds
[2023-02-16T13:53:40.646+0000] {processor.py:153} INFO - Started process (PID=77950) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:53:40.649+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:53:40.651+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:53:40.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:53:41.076+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:53:41.130+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:53:41.130+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:53:41.166+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:53:41.166+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:53:41.181+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.545 seconds
[2023-02-16T13:54:11.551+0000] {processor.py:153} INFO - Started process (PID=78021) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:54:11.557+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:54:11.560+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:54:11.560+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:54:11.952+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:54:11.980+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:54:11.980+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:54:11.999+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:54:11.999+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:54:12.011+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.471 seconds
[2023-02-16T13:54:42.233+0000] {processor.py:153} INFO - Started process (PID=78105) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:54:42.236+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:54:42.238+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:54:42.238+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:54:42.652+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:54:42.683+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:54:42.683+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:54:42.706+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:54:42.705+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:54:42.723+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.506 seconds
[2023-02-16T13:55:13.026+0000] {processor.py:153} INFO - Started process (PID=78177) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:55:13.029+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:55:13.031+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:55:13.030+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:55:13.406+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:55:13.432+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:55:13.432+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:55:13.468+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:55:13.468+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:55:13.482+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.469 seconds
[2023-02-16T13:55:43.637+0000] {processor.py:153} INFO - Started process (PID=78264) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:55:43.641+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:55:43.645+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:55:43.645+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:55:44.005+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:55:44.036+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:55:44.036+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:55:44.059+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:55:44.059+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:55:44.071+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.449 seconds
[2023-02-16T13:56:14.180+0000] {processor.py:153} INFO - Started process (PID=78335) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:56:14.182+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:56:14.184+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:56:14.184+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:56:14.688+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:56:14.752+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:56:14.752+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:56:14.790+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:56:14.790+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:56:14.818+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.647 seconds
[2023-02-16T13:56:45.207+0000] {processor.py:153} INFO - Started process (PID=78416) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:56:45.210+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:56:45.211+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:56:45.211+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:56:45.596+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:56:45.622+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:56:45.622+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:56:45.642+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:56:45.642+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:56:45.653+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.455 seconds
[2023-02-16T13:57:15.972+0000] {processor.py:153} INFO - Started process (PID=78497) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:57:15.976+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:57:15.980+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:57:15.979+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:57:16.949+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:57:17.077+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:57:17.076+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:57:17.156+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:57:17.156+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:57:17.201+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 1.251 seconds
[2023-02-16T13:57:47.848+0000] {processor.py:153} INFO - Started process (PID=78571) to work on /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:57:47.850+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_local_to_S3.py for tasks to queue
[2023-02-16T13:57:47.852+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:57:47.852+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:57:48.242+0000] {processor.py:753} INFO - DAG(s) dict_keys(['read_csv_drop_na_write_s3']) retrieved from /opt/airflow/dags/dag_local_to_S3.py
[2023-02-16T13:57:48.278+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:57:48.278+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-16T13:57:48.302+0000] {logging_mixin.py:137} INFO - [2023-02-16T13:57:48.302+0000] {dag.py:3441} INFO - Setting next_dagrun for read_csv_drop_na_write_s3 to None, run_after=None
[2023-02-16T13:57:48.339+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_local_to_S3.py took 0.507 seconds
