[2023-02-14T13:11:24.070+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag_v1.0.create_posgtres_table manual__2023-02-14T13:11:23.459593+00:00 [queued]>
[2023-02-14T13:11:24.077+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag_v1.0.create_posgtres_table manual__2023-02-14T13:11:23.459593+00:00 [queued]>
[2023-02-14T13:11:24.077+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T13:11:24.078+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-14T13:11:24.078+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T13:11:24.086+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_posgtres_table> on 2023-02-14 13:11:23.459593+00:00
[2023-02-14T13:11:24.091+0000] {standard_task_runner.py:55} INFO - Started process 3012 to run task
[2023-02-14T13:11:24.095+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag_v1.0', 'create_posgtres_table', 'manual__2023-02-14T13:11:23.459593+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpkh1x8gu2']
[2023-02-14T13:11:24.097+0000] {standard_task_runner.py:83} INFO - Job 49: Subtask create_posgtres_table
[2023-02-14T13:11:24.157+0000] {task_command.py:388} INFO - Running <TaskInstance: postgres_operator_dag_v1.0.create_posgtres_table manual__2023-02-14T13:11:23.459593+00:00 [running]> on host 01550fe0586b
[2023-02-14T13:11:24.222+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tlysenko
AIRFLOW_CTX_DAG_ID=postgres_operator_dag_v1.0
AIRFLOW_CTX_TASK_ID=create_posgtres_table
AIRFLOW_CTX_EXECUTION_DATE=2023-02-14T13:11:23.459593+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-14T13:11:23.459593+00:00
[2023-02-14T13:11:24.223+0000] {sql.py:254} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS dag_runs (
            dt date,
            dag_id character varying(250),
            primary key (dt, dag_id)
            )
        
[2023-02-14T13:11:24.231+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-02-14T13:11:24.348+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-02-14T13:11:24.381+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.inernal" to address: Name or service not known

[2023-02-14T13:11:24.391+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_operator_dag_v1.0, task_id=create_posgtres_table, execution_date=20230214T131123, start_date=20230214T131124, end_date=20230214T131124
[2023-02-14T13:11:24.398+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 49 for task create_posgtres_table (could not translate host name "host.docker.inernal" to address: Name or service not known
; 3012)
[2023-02-14T13:11:24.432+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-14T13:11:24.446+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
