[2023-02-22T16:26:01.384+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: csv_from_s3_to_s3_v01.test_get_file_from_s3 manual__2023-02-22T16:25:59.683397+00:00 [queued]>
[2023-02-22T16:26:01.395+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: csv_from_s3_to_s3_v01.test_get_file_from_s3 manual__2023-02-22T16:25:59.683397+00:00 [queued]>
[2023-02-22T16:26:01.396+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-22T16:26:01.397+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-22T16:26:01.397+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-22T16:26:01.410+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): test_get_file_from_s3> on 2023-02-22 16:25:59.683397+00:00
[2023-02-22T16:26:01.417+0000] {standard_task_runner.py:55} INFO - Started process 477 to run task
[2023-02-22T16:26:01.426+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'csv_from_s3_to_s3_v01', 'test_get_file_from_s3', 'manual__2023-02-22T16:25:59.683397+00:00', '--job-id', '222', '--raw', '--subdir', 'DAGS_FOLDER/dag_cleaning_via_s3.py', '--cfg-path', '/tmp/tmp1htbnq70']
[2023-02-22T16:26:01.429+0000] {standard_task_runner.py:83} INFO - Job 222: Subtask test_get_file_from_s3
[2023-02-22T16:26:01.537+0000] {task_command.py:388} INFO - Running <TaskInstance: csv_from_s3_to_s3_v01.test_get_file_from_s3 manual__2023-02-22T16:25:59.683397+00:00 [running]> on host e29b8426fc8e
[2023-02-22T16:26:01.657+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_from_s3_to_s3_v01
AIRFLOW_CTX_TASK_ID=test_get_file_from_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-02-22T16:25:59.683397+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-22T16:25:59.683397+00:00
[2023-02-22T16:26:01.660+0000] {logging_mixin.py:137} INFO - file name titanic.csv
[2023-02-22T16:26:01.677+0000] {base.py:73} INFO - Using connection ID 'AWS' for task execution.
[2023-02-22T16:26:01.678+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='AWS', conn_type='aws') credentials retrieved from login and password.
[2023-02-22T16:26:02.559+0000] {python.py:177} INFO - Done. Returned value was:      Survived  Pclass  ... Parents/Children Aboard     Fare
0           0       3  ...                       0   7.2500
1           1       1  ...                       0  71.2833
2           1       3  ...                       0   7.9250
3           1       1  ...                       0  53.1000
4           0       3  ...                       0   8.0500
..        ...     ...  ...                     ...      ...
882         0       2  ...                       0  13.0000
883         1       1  ...                       0  30.0000
884         0       3  ...                       2  23.4500
885         1       1  ...                       0  30.0000
886         0       3  ...                       0   7.7500

[887 rows x 8 columns]
[2023-02-22T16:26:02.604+0000] {xcom.py:635} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-02-22T16:26:02.606+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-02-22T16:26:02.621+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=csv_from_s3_to_s3_v01, task_id=test_get_file_from_s3, execution_date=20230222T162559, start_date=20230222T162601, end_date=20230222T162602
[2023-02-22T16:26:02.635+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 222 for task test_get_file_from_s3 (Object of type DataFrame is not JSON serializable; 477)
[2023-02-22T16:26:02.689+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-22T16:26:02.714+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
